App\Entity\City:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']
    longitude:
      - Range:
          min: -180
          max: 180
          groups: ['create', 'edit']

App\Entity\Forecast:
  properties:
    wind_speed:
      - Range:
          min: 0
          max: 100
          groups: [ 'create', 'edit' ]


